with open(r'd:\Portfolio_new\script.js', 'r', encoding='utf-8') as f:
    content = f.read()

start_marker = '// Animated Halftone Portrait Background'
end_marker   = '// Typewriter effect for About heading'

start_idx = content.find(start_marker)
end_idx   = content.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print(f'MARKERS NOT FOUND: start={start_idx}, end={end_idx}')
    exit(1)

new_block = (
    "// Animated Halftone Portrait Background — optimised with pre-render + dirty flag\n"
    "document.addEventListener(\"DOMContentLoaded\", () => {\n"
    "    const canvas = document.getElementById('ascii-canvas');\n"
    "    if (!canvas) return;\n"
    "\n"
    "    const ctx = canvas.getContext('2d', { willReadFrequently: true });\n"
    "    canvas.style.willChange = 'contents'; // hint browser to GPU-layer the canvas\n"
    "\n"
    "    const image = new Image();\n"
    "    image.src = 'linkedinPhoto.png';\n"
    "\n"
    "    // Each cell: { alpha: 0..1, r, g, b: 0-255 }\n"
    "    let dotGrid = [];\n"
    "    let cols = 0, rows = 0, blockSize = 5;\n"
    "\n"
    "    // Pre-rendered offscreen of ALL white dots (drawn once, blitted every frame)\n"
    "    let staticCanvas = null;\n"
    "    let staticCtx    = null;\n"
    "\n"
    "    // Mouse state\n"
    "    let mouseX = -9999, mouseY = -9999;\n"
    "    let dirty  = true;  // only redraw when something changed\n"
    "    const COLOR_RADIUS = 120;\n"
    "\n"
    "    window.addEventListener('mousemove', (e) => {\n"
    "        const rect = canvas.getBoundingClientRect();\n"
    "        const nx = e.clientX - rect.left;\n"
    "        const ny = e.clientY - rect.top;\n"
    "        if (nx !== mouseX || ny !== mouseY) {\n"
    "            mouseX = nx;\n"
    "            mouseY = ny;\n"
    "            dirty  = true;\n"
    "        }\n"
    "    });\n"
    "\n"
    "    document.addEventListener('mouseleave', () => {\n"
    "        mouseX = -9999;\n"
    "        mouseY = -9999;\n"
    "        dirty  = true;\n"
    "    });\n"
    "\n"
    "    image.onload = () => {\n"
    "\n"
    "        function initAscii() {\n"
    "            canvas.width  = window.innerWidth;\n"
    "            canvas.height = window.innerHeight;\n"
    "\n"
    "            blockSize = canvas.width < 768 ? 4 : 5;\n"
    "            cols = Math.floor(canvas.width  / blockSize);\n"
    "            rows = Math.floor(canvas.height / blockSize);\n"
    "\n"
    "            // Offscreen 1: black bg for luminance\n"
    "            const grayOff = document.createElement('canvas');\n"
    "            grayOff.width  = cols;\n"
    "            grayOff.height = rows;\n"
    "            const grayCtx = grayOff.getContext('2d');\n"
    "\n"
    "            // Offscreen 2: transparent for original RGB color\n"
    "            const colorOff = document.createElement('canvas');\n"
    "            colorOff.width  = cols;\n"
    "            colorOff.height = rows;\n"
    "            const colorCtx = colorOff.getContext('2d');\n"
    "\n"
    "            const imgRatio    = image.width / image.height;\n"
    "            const canvasRatio = cols / rows;\n"
    "            let drawWidth, drawHeight, offsetX, offsetY;\n"
    "            const minOffsetY = 90 / blockSize;\n"
    "\n"
    "            if (canvasRatio > 1) {\n"
    "                drawWidth  = cols * 0.52;\n"
    "                drawHeight = drawWidth / imgRatio;\n"
    "                offsetX    = cols - drawWidth - (cols * 0.01);\n"
    "                offsetY    = Math.max((rows - drawHeight) * 0.38, minOffsetY);\n"
    "            } else {\n"
    "                drawWidth  = cols * 0.95;\n"
    "                drawHeight = drawWidth / imgRatio;\n"
    "                offsetX    = (cols - drawWidth) / 2;\n"
    "                offsetY    = Math.max((rows - drawHeight) * 0.3, minOffsetY);\n"
    "            }\n"
    "\n"
    "            grayCtx.fillStyle = 'black';\n"
    "            grayCtx.fillRect(0, 0, cols, rows);\n"
    "            grayCtx.drawImage(image, offsetX, offsetY, drawWidth, drawHeight);\n"
    "\n"
    "            colorCtx.clearRect(0, 0, cols, rows);\n"
    "            colorCtx.drawImage(image, offsetX, offsetY, drawWidth, drawHeight);\n"
    "\n"
    "            const grayData  = grayOff.getContext('2d').getImageData(0, 0, cols, rows).data;\n"
    "            const colorData = colorCtx.getImageData(0, 0, cols, rows).data;\n"
    "\n"
    "            const portraitCX = offsetX + drawWidth  * 0.50;\n"
    "            const portraitCY = offsetY + drawHeight * 0.40;\n"
    "            const rx = drawWidth  * 0.56;\n"
    "            const ry = drawHeight * 0.54;\n"
    "\n"
    "            dotGrid = [];\n"
    "            for (let y = 0; y < rows; y++) {\n"
    "                const row = [];\n"
    "                for (let x = 0; x < cols; x++) {\n"
    "                    const i = (y * cols + x) * 4;\n"
    "                    const gR = grayData[i], gG = grayData[i+1], gB = grayData[i+2], gA = grayData[i+3];\n"
    "                    let brightness = 0;\n"
    "                    if (gA > 0) {\n"
    "                        brightness = (gR * 0.299 + gG * 0.587 + gB * 0.114) * (gA / 255);\n"
    "                        brightness = Math.min(255, Math.max(0, (brightness - 15) * 1.4));\n"
    "                    }\n"
    "                    const ndx  = (x - portraitCX) / rx;\n"
    "                    const ndy  = (y - portraitCY) / ry;\n"
    "                    const dist = Math.sqrt(ndx * ndx + ndy * ndy);\n"
    "                    let fade = Math.max(0, 1.0 - dist);\n"
    "                    fade = fade * fade * (3 - 2 * fade);\n"
    "                    fade = fade * fade * (3 - 2 * fade);\n"
    "                    row.push({\n"
    "                        alpha: (brightness / 255) * fade,\n"
    "                        r: colorData[i], g: colorData[i+1], b: colorData[i+2]\n"
    "                    });\n"
    "                }\n"
    "                dotGrid.push(row);\n"
    "            }\n"
    "\n"
    "            // --- Pre-render all white dots into a static offscreen canvas ---\n"
    "            staticCanvas = document.createElement('canvas');\n"
    "            staticCanvas.width  = canvas.width;\n"
    "            staticCanvas.height = canvas.height;\n"
    "            staticCtx = staticCanvas.getContext('2d');\n"
    "\n"
    "            const maxR = (blockSize * 0.9) / 2;\n"
    "            // Build one big path for all white dots of the same alpha bucket\n"
    "            // Group dots into ~20 alpha buckets to minimise fillStyle changes\n"
    "            const BUCKETS = 20;\n"
    "            const bucketPaths  = new Array(BUCKETS).fill(null).map(() => []);\n"
    "\n"
    "            for (let y = 0; y < rows; y++) {\n"
    "                for (let x = 0; x < cols; x++) {\n"
    "                    const alpha = dotGrid[y][x].alpha;\n"
    "                    if (alpha < 0.008) continue;\n"
    "                    const bucket = Math.min(BUCKETS - 1, Math.floor(alpha * BUCKETS));\n"
    "                    bucketPaths[bucket].push({\n"
    "                        cx: x * blockSize + blockSize / 2,\n"
    "                        cy: y * blockSize + blockSize / 2,\n"
    "                        r:  maxR * Math.sqrt(alpha),\n"
    "                        a:  Math.min(1, alpha * 1.2)\n"
    "                    });\n"
    "                }\n"
    "            }\n"
    "\n"
    "            for (let b = 0; b < BUCKETS; b++) {\n"
    "                if (bucketPaths[b].length === 0) continue;\n"
    "                const repAlpha = bucketPaths[b][0].a;\n"
    "                staticCtx.fillStyle = 'rgba(255,255,255,' + repAlpha + ')';\n"
    "                staticCtx.beginPath();\n"
    "                for (const d of bucketPaths[b]) {\n"
    "                    staticCtx.moveTo(d.cx + d.r, d.cy);\n"
    "                    staticCtx.arc(d.cx, d.cy, d.r, 0, Math.PI * 2);\n"
    "                }\n"
    "                staticCtx.fill();\n"
    "            }\n"
    "\n"
    "            dirty = true;\n"
    "        }\n"
    "\n"
    "        function draw() {\n"
    "            requestAnimationFrame(draw); // schedule next frame first\n"
    "\n"
    "            if (!dirty || !staticCanvas) return; // nothing changed — skip work\n"
    "            dirty = false;\n"
    "\n"
    "            // 1. Blit the pre-rendered white-dot canvas (single GPU call)\n"
    "            ctx.clearRect(0, 0, canvas.width, canvas.height);\n"
    "            ctx.drawImage(staticCanvas, 0, 0);\n"
    "\n"
    "            // 2. Color spotlight — only iterate cells inside a bounding box around cursor\n"
    "            if (mouseX >= 0 && mouseX < canvas.width && mouseY >= 0 && mouseY < canvas.height) {\n"
    "                const maxR         = (blockSize * 0.9) / 2;\n"
    "                const colorRadSq   = COLOR_RADIUS * COLOR_RADIUS;\n"
    "\n"
    "                const minCol = Math.max(0,        Math.floor((mouseX - COLOR_RADIUS) / blockSize));\n"
    "                const maxCol = Math.min(cols - 1, Math.ceil ((mouseX + COLOR_RADIUS) / blockSize));\n"
    "                const minRow = Math.max(0,        Math.floor((mouseY - COLOR_RADIUS) / blockSize));\n"
    "                const maxRow = Math.min(rows - 1, Math.ceil ((mouseY + COLOR_RADIUS) / blockSize));\n"
    "\n"
    "                for (let y = minRow; y <= maxRow; y++) {\n"
    "                    for (let x = minCol; x <= maxCol; x++) {\n"
    "                        const cell  = dotGrid[y][x];\n"
    "                        if (cell.alpha < 0.008) continue;\n"
    "\n"
    "                        const cx = x * blockSize + blockSize / 2;\n"
    "                        const cy = y * blockSize + blockSize / 2;\n"
    "                        const dx = cx - mouseX, dy = cy - mouseY;\n"
    "                        const dSq = dx * dx + dy * dy;\n"
    "                        if (dSq >= colorRadSq) continue;\n"
    "\n"
    "                        // Smoothstep blend factor: 1 at cursor center, 0 at radius edge\n"
    "                        const rawT = 1 - Math.sqrt(dSq) / COLOR_RADIUS;\n"
    "                        const t    = rawT * rawT * (3 - 2 * rawT);\n"
    "                        const dr   = Math.round(255 + (cell.r - 255) * t);\n"
    "                        const dg   = Math.round(255 + (cell.g - 255) * t);\n"
    "                        const db   = Math.round(255 + (cell.b - 255) * t);\n"
    "\n"
    "                        // Erase the white dot, redraw with color\n"
    "                        ctx.clearRect(x * blockSize, y * blockSize, blockSize, blockSize);\n"
    "                        ctx.beginPath();\n"
    "                        ctx.arc(cx, cy, maxR * Math.sqrt(cell.alpha), 0, Math.PI * 2);\n"
    "                        ctx.fillStyle = 'rgba(' + dr + ',' + dg + ',' + db + ',' + Math.min(1, cell.alpha * 1.2) + ')';\n"
    "                        ctx.fill();\n"
    "                    }\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "\n"
    "        window.addEventListener('resize', () => {\n"
    "            initAscii();\n"
    "        });\n"
    "\n"
    "        initAscii();\n"
    "        draw();\n"
    "    };\n"
    "});\n"
    "\n"
)

new_content = content[:start_idx] + new_block + content[end_idx:]

with open(r'd:\Portfolio_new\script.js', 'w', encoding='utf-8') as f:
    f.write(new_content)

print('Done. Performance-optimised halftone written.')
