// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './unknown.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };
import glyphDataById from './glyphDataById.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Unknown',
  lineCap: 'butt',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Unknown'; src: url(${fontUrl}); }`,
  unitsPerEm: 2048,
  ascender: 1905,
  descender: -1084,
  glyphData,
  glyphDataById,
  features: ["frac","liga"],
} as const;

export default bundle;
